"""Composers whose music is in the public domain (died 1954 or earlier),
keyed by a folded surname, with a full name and an era for display.
Traditional and anonymous music is public domain too (see TRAD)."""
PD = {
 "byrd": ("William Byrd", "Renaissance"), "gibbons": ("Orlando Gibbons", "Renaissance"), "john bull": ("John Bull", "Renaissance"),
 "sweelinck": ("Jan Pieterszoon Sweelinck", "Renaissance"), "dowland": ("John Dowland", "Renaissance"), "farnaby": ("Giles Farnaby", "Renaissance"),
 "frescobaldi": ("Girolamo Frescobaldi", "Baroque"), "froberger": ("Johann Jakob Froberger", "Baroque"), "purcell": ("Henry Purcell", "Baroque"),
 "pachelbel": ("Johann Pachelbel", "Baroque"), "buxtehude": ("Dieterich Buxtehude", "Baroque"), "couperin": ("François Couperin", "Baroque"),
 "rameau": ("Jean-Philippe Rameau", "Baroque"), "daquin": ("Louis-Claude Daquin", "Baroque"), "lully": ("Jean-Baptiste Lully", "Baroque"),
 "bach": ("Johann Sebastian Bach", "Baroque"), "handel": ("George Frideric Handel", "Baroque"), "haendel": ("George Frideric Handel", "Baroque"), "hndel": ("George Frideric Handel", "Baroque"),
 "scarlatti": ("Domenico Scarlatti", "Baroque"), "telemann": ("Georg Philipp Telemann", "Baroque"), "vivaldi": ("Antonio Vivaldi", "Baroque"),
 "corelli": ("Arcangelo Corelli", "Baroque"), "albinoni": ("Tomaso Albinoni", "Baroque"), "marcello": ("Alessandro Marcello", "Baroque"),
 "soler": ("Antonio Soler", "Baroque"), "pergolesi": ("Giovanni Battista Pergolesi", "Baroque"), "zipoli": ("Domenico Zipoli", "Baroque"),
 "kuhnau": ("Johann Kuhnau", "Baroque"), "graupner": ("Christoph Graupner", "Baroque"), "petzold": ("Christian Petzold", "Baroque"),
 "haydn": ("Joseph Haydn", "Classical"), "mozart": ("Wolfgang Amadeus Mozart", "Classical"), "clementi": ("Muzio Clementi", "Classical"),
 "kuhlau": ("Friedrich Kuhlau", "Classical"), "diabelli": ("Anton Diabelli", "Classical"), "dussek": ("Jan Ladislav Dussek", "Classical"),
 "hummel": ("Johann Nepomuk Hummel", "Classical"), "gluck": ("Christoph Willibald Gluck", "Classical"), "cimarosa": ("Domenico Cimarosa", "Classical"),
 "boccherini": ("Luigi Boccherini", "Classical"), "salieri": ("Antonio Salieri", "Classical"), "john field": ("John Field", "Early Romantic"),
 "beethoven": ("Ludwig van Beethoven", "Early Romantic"), "schubert": ("Franz Schubert", "Early Romantic"), "carl maria von weber": ("Carl Maria von Weber", "Early Romantic"),
 "czerny": ("Carl Czerny", "Early Romantic"), "mendelssohn": ("Felix Mendelssohn", "Romantic"), "hensel": ("Fanny Hensel", "Romantic"),
 "chopin": ("Frédéric Chopin", "Romantic"), "schumann": ("Robert Schumann", "Romantic"), "liszt": ("Franz Liszt", "Romantic"),
 "brahms": ("Johannes Brahms", "Romantic"), "alkan": ("Charles-Valentin Alkan", "Romantic"), "thalberg": ("Sigismond Thalberg", "Romantic"),
 "heller": ("Stephen Heller", "Romantic"), "burgmuller": ("Friedrich Burgmüller", "Romantic"), "burgmueller": ("Friedrich Burgmüller", "Romantic"),
 "gurlitt": ("Cornelius Gurlitt", "Romantic"), "streabbog": ("Jean Louis Streabbog", "Romantic"), "lemoine": ("Henry Lemoine", "Romantic"),
 "duvernoy": ("Jean-Baptiste Duvernoy", "Romantic"), "bertini": ("Henri Bertini", "Romantic"), "lebert": ("Sigmund Lebert", "Romantic"),
 "kohler": ("Louis Köhler", "Romantic"), "loeschhorn": ("Albert Loeschhorn", "Romantic"), "hanon": ("Charles-Louis Hanon", "Romantic"),
 "tchaikovsky": ("Pyotr Ilyich Tchaikovsky", "Romantic"), "tschaikowsky": ("Pyotr Ilyich Tchaikovsky", "Romantic"), "chaikovsky": ("Pyotr Ilyich Tchaikovsky", "Romantic"),
 "mussorgsky": ("Modest Mussorgsky", "Romantic"), "borodin": ("Alexander Borodin", "Romantic"), "rimsky": ("Nikolai Rimsky-Korsakov", "Romantic"),
 "balakirev": ("Mily Balakirev", "Romantic"), "glinka": ("Mikhail Glinka", "Romantic"), "rubinstein": ("Anton Rubinstein", "Romantic"),
 "lyadov": ("Anatoly Lyadov", "Romantic"), "liadov": ("Anatoly Lyadov", "Romantic"), "arensky": ("Anton Arensky", "Romantic"),
 "scriabin": ("Alexander Scriabin", "Late Romantic"), "skryabin": ("Alexander Scriabin", "Late Romantic"), "rachmaninoff": ("Sergei Rachmaninoff", "Late Romantic"),
 "rachmaninov": ("Sergei Rachmaninoff", "Late Romantic"), "glazunov": ("Alexander Glazunov", "Late Romantic"), "medtner": ("Nikolai Medtner", "Late Romantic"),
 "grieg": ("Edvard Grieg", "Romantic"), "sinding": ("Christian Sinding", "Romantic"), "dvorak": ("Antonín Dvořák", "Romantic"), "smetana": ("Bedřich Smetana", "Romantic"),
 "fibich": ("Zdeněk Fibich", "Romantic"), "janacek": ("Leoš Janáček", "Late Romantic"), "franck": ("César Franck", "Romantic"),
 "saint saens": ("Camille Saint-Saëns", "Romantic"), "saintsaens": ("Camille Saint-Saëns", "Romantic"), "bizet": ("Georges Bizet", "Romantic"),
 "gounod": ("Charles Gounod", "Romantic"), "massenet": ("Jules Massenet", "Romantic"), "delibes": ("Léo Delibes", "Romantic"),
 "offenbach": ("Jacques Offenbach", "Romantic"), "faure": ("Gabriel Fauré", "Late Romantic"), "chaminade": ("Cécile Chaminade", "Late Romantic"),
 "chabrier": ("Emmanuel Chabrier", "Romantic"), "godard": ("Benjamin Godard", "Romantic"), "debussy": ("Claude Debussy", "Impressionist"),
 "ravel": ("Maurice Ravel", "Impressionist"), "satie": ("Erik Satie", "Impressionist"), "dukas": ("Paul Dukas", "Impressionist"),
 "roussel": ("Albert Roussel", "Modern"), "albeniz": ("Isaac Albéniz", "Romantic"), "granados": ("Enrique Granados", "Romantic"),
 "falla": ("Manuel de Falla", "Modern"), "turina": ("Joaquín Turina", "Modern"), "tarrega": ("Francisco Tárrega", "Romantic"),
 "elgar": ("Edward Elgar", "Late Romantic"), "sullivan": ("Arthur Sullivan", "Romantic"), "holst": ("Gustav Holst", "Modern"),
 "delius": ("Frederick Delius", "Late Romantic"), "coleridge taylor": ("Samuel Coleridge-Taylor", "Late Romantic"), "macdowell": ("Edward MacDowell", "Late Romantic"),
 "gottschalk": ("Louis Moreau Gottschalk", "Romantic"), "joplin": ("Scott Joplin", "Ragtime"), "joseph lamb": ("Joseph Lamb", "Ragtime"),
 "james scott": ("James Scott", "Ragtime"), "stephen foster": ("Stephen Foster", "Romantic"), "sousa": ("John Philip Sousa", "Romantic"),
 "gershwin": ("George Gershwin", "Modern"), "jelly roll morton": ("Jelly Roll Morton", "Ragtime"), "waller": ("Fats Waller", "Modern"),
 "bartok": ("Béla Bartók", "Modern"), "prokofiev": ("Sergei Prokofiev", "Modern"), "reger": ("Max Reger", "Late Romantic"),
 "mahler": ("Gustav Mahler", "Late Romantic"), "wagner": ("Richard Wagner", "Romantic"), "verdi": ("Giuseppe Verdi", "Romantic"),
 "puccini": ("Giacomo Puccini", "Late Romantic"), "rossini": ("Gioachino Rossini", "Romantic"), "vincenzo bellini": ("Vincenzo Bellini", "Romantic"),
 "donizetti": ("Gaetano Donizetti", "Romantic"), "johann strauss": ("Johann Strauss II", "Romantic"), "lanner": ("Joseph Lanner", "Romantic"),
 "waldteufel": ("Émile Waldteufel", "Romantic"), "ivanovici": ("Ion Ivanovici", "Romantic"), "badarzewska": ("Tekla Bądarzewska", "Romantic"),
 "moszkowski": ("Moritz Moszkowski", "Romantic"), "paderewski": ("Ignacy Jan Paderewski", "Late Romantic"), "szymanowska": ("Maria Szymanowska", "Early Romantic"),
 "oginski": ("Michał Kleofas Ogiński", "Classical"), "gustav lange": ("Gustav Lange", "Romantic"), "ellmenreich": ("Albert Ellmenreich", "Romantic"),
 "schytte": ("Ludvig Schytte", "Romantic"), "niels gade": ("Niels Gade", "Romantic"), "nielsen": ("Carl Nielsen", "Late Romantic"),
 "sibelius": ("Jean Sibelius", "Late Romantic"), "albeniz isaac": ("Isaac Albéniz", "Romantic"), "lecuona": ("Ernesto Lecuona", "Modern"),
 "nazareth": ("Ernesto Nazareth", "Romantic"), "gonzaga": ("Chiquinha Gonzaga", "Romantic"), "manuel ponce": ("Manuel Ponce", "Modern"),
 "juventino rosas": ("Juventino Rosas", "Romantic"), "kirkpatrick": ("William J. Kirkpatrick", "Romantic"), "william bradbury": ("William Bradbury", "Romantic"),
 "lowell mason": ("Lowell Mason", "Romantic"), "robert lowry": ("Robert Lowry", "Romantic"), "w h doane": ("William Howard Doane", "Romantic"),
 "ira d sankey": ("Ira D. Sankey", "Romantic"), "philip bliss": ("Philip Bliss", "Romantic"), "dykes": ("John Bacchus Dykes", "Romantic"),
 "mompou": None, "glass": None, "einaudi": None, "tiersen": None, "yiruma": None, "hisaishi": None, "williams": None, "zimmer": None,
}
TRAD = ("traditional", "folk song", "folksong", "anonymous", "volkslied")
